update pre commit hooks

diff --git a/git/hooks/ruby-pre-commit b/git/hooks/ruby-pre-commit
--- a/git/hooks/ruby-pre-commit
+++ b/git/hooks/ruby-pre-commit
@@ -18,13 +18,13 @@ scriptPath="hydra_clients/insights_home/node_modules/husky/lib/runner/bin.js"
 hookName=`basename "$0"`
 gitParams="$*"
 
-if ! command -v node >/dev/null 2>&1; then
-  echo "Can't find node in PATH, trying to find a node binary on your system"
-fi
+# if ! command -v node >/dev/null 2>&1; then
+#   echo "Can't find node in PATH, trying to find a node binary on your system"
+# fi
 
-if [ -f $scriptPath ]; then
-  hydra_clients/insights_home/node_modules/run-node/run-node $scriptPath $hookName "$gitParams"
-else
-  echo "Can't find Husky, skipping $hookName hook"
-  echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
-fi
+# if [ -f $scriptPath ]; then
+#   hydra_clients/insights_home/node_modules/run-node/run-node $scriptPath $hookName "$gitParams"
+# else
+#   echo "Can't find Husky, skipping $hookName hook"
+#   echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
+# fi
